version: '2'
services:
    portalapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/PortalApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=PortalApp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
